<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>$(BuildVersion)</Version>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Platforms>x64</Platforms>
        <LangVersion>12.0</LangVersion>
        <Nullable>enable</Nullable>

        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/JoeFwd/Bannerlord.ExpandedTemplate</PackageProjectUrl>

        <CopyLocalLockFileAssemblies>True</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.44.1"/>
        <PackageReference Include="Bannerlord.ReferenceAssemblies.Core" Version="$(GameVersion).*-*" PrivateAssets="All"/>
        
        
        <ProjectReference Include="..\Bannerlord.ExpandedTemplate.Integration\Bannerlord.ExpandedTemplate.Integration.csproj" />
    </ItemGroup>

    <Target Name="ILRepacker" AfterTargets="Build">
        <ItemGroup>
            <InputAssemblies Include="$(OutputPath)\*.dll"/>
        </ItemGroup>

        <ILRepack
                Parallel="true"
                InputAssemblies="@(InputAssemblies)"
                TargetKind="Dll"
                OutputFile="$(OutputPath)\$(AssemblyName).dll"
        />

<!--        <ILRepack-->
<!--                Parallel="true"-->
<!--                Internalize="true"-->
<!--                InputAssemblies="@(InputAssemblies)"-->
<!--                TargetKind="Dll"-->
<!--                OutputFile="$(OutputPath)\$(AssemblyName).dll"-->
<!--        />-->
    </Target>

    <Target Name="CleanBeforeBuild" AfterTargets="ILRepacker">
        <ItemGroup>
            <FilesToDelete Include="$(OutputPath)\*.*"
                           Exclude="$(OutputPath)\$(AssemblyName).dll"/>
        </ItemGroup>
        <Message Text="Deleting file: %(FilesToDelete.Identity)" Importance="High"/>

        <Delete Files="@(FilesToDelete)"/>
        <!--        <Message Text="Renaming $(OutputPath)\$(AssemblyName).Fat.dll to $(OutputPath)\$(AssemblyName).dll" Importance="High"/>-->
        <!--        <Move SourceFiles="$(OutputPath)\$(AssemblyName).Fat.dll"-->
        <!--              DestinationFiles="$(OutputPath)\$(AssemblyName).dll"-->
        <!--              OverwriteReadOnlyFiles="true"/>-->
    </Target>

</Project>
