name: Test

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true
  push:
    branches:
      - dev

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore Bannerlord.ExpandedTemplate.sln

      - name: Build solution
        run: dotnet build Bannerlord.ExpandedTemplate.sln --configuration Release --no-restore

      - name: Run unit tests with coverage
        run: |
          dotnet test --collect:"XPlat Code Coverage" --results-directory ./coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.3.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: ./coverage/*/coverage.cobertura.xml
          fail_ci_if_error: true